// Comprehensive Analytics Dummy Data for HR Dashboard

// 1. Department Performance Data
export const departmentPerformanceData = [
  {
    department: "Engineering",
    averageRating: 4.3,
    employeeCount: 45,
    topPerformers: 18,
    satisfactionScore: 92,
    retentionRate: 94,
  },
  {
    department: "Marketing",
    averageRating: 3.9,
    employeeCount: 28,
    topPerformers: 12,
    satisfactionScore: 87,
    retentionRate: 89,
  },
  {
    department: "Sales",
    averageRating: 4.1,
    employeeCount: 35,
    topPerformers: 16,
    satisfactionScore: 85,
    retentionRate: 91,
  },
  {
    department: "HR",
    averageRating: 4.0,
    employeeCount: 15,
    topPerformers: 7,
    satisfactionScore: 90,
    retentionRate: 96,
  },
  {
    department: "Finance",
    averageRating: 3.8,
    employeeCount: 22,
    topPerformers: 9,
    satisfactionScore: 83,
    retentionRate: 88,
  },
  {
    department: "Operations",
    averageRating: 3.7,
    employeeCount: 31,
    topPerformers: 11,
    satisfactionScore: 81,
    retentionRate: 85,
  },
  {
    department: "Customer Support",
    averageRating: 4.2,
    employeeCount: 24,
    topPerformers: 11,
    satisfactionScore: 88,
    retentionRate: 87,
  },
  {
    department: "Product",
    averageRating: 4.4,
    employeeCount: 19,
    topPerformers: 10,
    satisfactionScore: 94,
    retentionRate: 93,
  },
]

// 2. Bookmark Trends Data (12 months)
export const bookmarkTrendsData = [
  {
    month: "Jan 2024",
    bookmarksCreated: 145,
    userEngagement: 78,
    avgTimeSpent: 12.5,
    activeUsers: 89,
    clickThroughRate: 65,
  },
  {
    month: "Feb 2024",
    bookmarksCreated: 167,
    userEngagement: 82,
    avgTimeSpent: 14.2,
    activeUsers: 95,
    clickThroughRate: 68,
  },
  {
    month: "Mar 2024",
    bookmarksCreated: 189,
    userEngagement: 85,
    avgTimeSpent: 15.8,
    activeUsers: 102,
    clickThroughRate: 72,
  },
  {
    month: "Apr 2024",
    bookmarksCreated: 156,
    userEngagement: 79,
    avgTimeSpent: 13.1,
    activeUsers: 87,
    clickThroughRate: 63,
  },
  {
    month: "May 2024",
    bookmarksCreated: 203,
    userEngagement: 88,
    avgTimeSpent: 16.7,
    activeUsers: 108,
    clickThroughRate: 75,
  },
  {
    month: "Jun 2024",
    bookmarksCreated: 234,
    userEngagement: 91,
    avgTimeSpent: 18.3,
    activeUsers: 115,
    clickThroughRate: 78,
  },
  {
    month: "Jul 2024",
    bookmarksCreated: 198,
    userEngagement: 86,
    avgTimeSpent: 15.9,
    activeUsers: 99,
    clickThroughRate: 71,
  },
  {
    month: "Aug 2024",
    bookmarksCreated: 221,
    userEngagement: 89,
    avgTimeSpent: 17.4,
    activeUsers: 112,
    clickThroughRate: 76,
  },
  {
    month: "Sep 2024",
    bookmarksCreated: 267,
    userEngagement: 93,
    avgTimeSpent: 19.8,
    activeUsers: 125,
    clickThroughRate: 81,
  },
  {
    month: "Oct 2024",
    bookmarksCreated: 245,
    userEngagement: 90,
    avgTimeSpent: 18.1,
    activeUsers: 118,
    clickThroughRate: 77,
  },
  {
    month: "Nov 2024",
    bookmarksCreated: 289,
    userEngagement: 95,
    avgTimeSpent: 21.2,
    activeUsers: 132,
    clickThroughRate: 84,
  },
  {
    month: "Dec 2024",
    bookmarksCreated: 312,
    userEngagement: 97,
    avgTimeSpent: 22.6,
    activeUsers: 140,
    clickThroughRate: 87,
  },
]

// 3. Performance Distribution Data
export const performanceDistributionData = [
  {
    rating: "Excellent (4.5-5.0)",
    count: 42,
    percentage: 19.1,
    color: "#10b981",
    employees: ["Sarah Johnson", "Michael Chen", "Emily Rodriguez"],
  },
  {
    rating: "Good (3.5-4.4)",
    count: 89,
    percentage: 40.5,
    color: "#06b6d4",
    employees: ["David Wilson", "Lisa Park", "James Miller"],
  },
  {
    rating: "Average (2.5-3.4)",
    count: 67,
    percentage: 30.5,
    color: "#f59e0b",
    employees: ["Anna Thompson", "Robert Lee", "Maria Garcia"],
  },
  {
    rating: "Needs Improvement (1.5-2.4)",
    count: 18,
    percentage: 8.2,
    color: "#ef4444",
    employees: ["Tom Anderson", "Jennifer Brown"],
  },
  {
    rating: "Poor (1.0-1.4)",
    count: 4,
    percentage: 1.8,
    color: "#dc2626",
    employees: ["Alex Turner"],
  },
]

// 4. Skills Analysis Data
export const skillsAnalysisData = [
  {
    skill: "JavaScript",
    currentProficiency: 78,
    marketDemand: 95,
    gap: -17,
    priority: "High",
    employeesWithSkill: 34,
  },
  {
    skill: "Project Management",
    currentProficiency: 85,
    marketDemand: 88,
    gap: -3,
    priority: "Medium",
    employeesWithSkill: 42,
  },
  {
    skill: "Data Analysis",
    currentProficiency: 72,
    marketDemand: 92,
    gap: -20,
    priority: "High",
    employeesWithSkill: 28,
  },
  {
    skill: "Python",
    currentProficiency: 65,
    marketDemand: 89,
    gap: -24,
    priority: "High",
    employeesWithSkill: 22,
  },
  {
    skill: "Leadership",
    currentProficiency: 82,
    marketDemand: 85,
    gap: -3,
    priority: "Medium",
    employeesWithSkill: 38,
  },
  {
    skill: "Digital Marketing",
    currentProficiency: 79,
    marketDemand: 83,
    gap: -4,
    priority: "Medium",
    employeesWithSkill: 25,
  },
  {
    skill: "Cloud Computing",
    currentProficiency: 68,
    marketDemand: 94,
    gap: -26,
    priority: "High",
    employeesWithSkill: 19,
  },
  {
    skill: "UX/UI Design",
    currentProficiency: 74,
    marketDemand: 87,
    gap: -13,
    priority: "Medium",
    employeesWithSkill: 16,
  },
  {
    skill: "Machine Learning",
    currentProficiency: 58,
    marketDemand: 91,
    gap: -33,
    priority: "Critical",
    employeesWithSkill: 12,
  },
  {
    skill: "Communication",
    currentProficiency: 88,
    marketDemand: 90,
    gap: -2,
    priority: "Low",
    employeesWithSkill: 156,
  },
]

// 5. Monthly Performance Trends Data
export const monthlyPerformanceTrendsData = [
  {
    month: "Jan 2024",
    averageRating: 3.8,
    projectCompletionRate: 87,
    customerSatisfaction: 82,
    employeeEngagement: 78,
    revenueGrowth: 5.2,
  },
  {
    month: "Feb 2024",
    averageRating: 3.9,
    projectCompletionRate: 89,
    customerSatisfaction: 84,
    employeeEngagement: 80,
    revenueGrowth: 6.1,
  },
  {
    month: "Mar 2024",
    averageRating: 4.0,
    projectCompletionRate: 91,
    customerSatisfaction: 86,
    employeeEngagement: 82,
    revenueGrowth: 7.3,
  },
  {
    month: "Apr 2024",
    averageRating: 3.9,
    projectCompletionRate: 88,
    customerSatisfaction: 83,
    employeeEngagement: 79,
    revenueGrowth: 5.8,
  },
  {
    month: "May 2024",
    averageRating: 4.1,
    projectCompletionRate: 93,
    customerSatisfaction: 87,
    employeeEngagement: 84,
    revenueGrowth: 8.2,
  },
  {
    month: "Jun 2024",
    averageRating: 4.2,
    projectCompletionRate: 95,
    customerSatisfaction: 89,
    employeeEngagement: 86,
    revenueGrowth: 9.1,
  },
  {
    month: "Jul 2024",
    averageRating: 4.0,
    projectCompletionRate: 90,
    customerSatisfaction: 85,
    employeeEngagement: 83,
    revenueGrowth: 7.5,
  },
  {
    month: "Aug 2024",
    averageRating: 4.1,
    projectCompletionRate: 92,
    customerSatisfaction: 88,
    employeeEngagement: 85,
    revenueGrowth: 8.7,
  },
  {
    month: "Sep 2024",
    averageRating: 4.3,
    projectCompletionRate: 96,
    customerSatisfaction: 91,
    employeeEngagement: 88,
    revenueGrowth: 10.2,
  },
  {
    month: "Oct 2024",
    averageRating: 4.2,
    projectCompletionRate: 94,
    customerSatisfaction: 90,
    employeeEngagement: 87,
    revenueGrowth: 9.6,
  },
  {
    month: "Nov 2024",
    averageRating: 4.4,
    projectCompletionRate: 97,
    customerSatisfaction: 92,
    employeeEngagement: 89,
    revenueGrowth: 11.3,
  },
  {
    month: "Dec 2024",
    averageRating: 4.3,
    projectCompletionRate: 95,
    customerSatisfaction: 91,
    employeeEngagement: 88,
    revenueGrowth: 10.8,
  },
]

// 6. Department Growth Data (Quarterly)
export const departmentGrowthData = [
  {
    department: "Engineering",
    q1Revenue: 2850000,
    q2Revenue: 3120000,
    q3Revenue: 3450000,
    q4Revenue: 3780000,
    q1Completion: 89,
    q2Completion: 92,
    q3Completion: 95,
    q4Completion: 97,
    q1Satisfaction: 87,
    q2Satisfaction: 90,
    q3Satisfaction: 92,
    q4Satisfaction: 94,
  },
  {
    department: "Marketing",
    q1Revenue: 1650000,
    q2Revenue: 1820000,
    q3Revenue: 2100000,
    q4Revenue: 2350000,
    q1Completion: 85,
    q2Completion: 88,
    q3Completion: 91,
    q4Completion: 93,
    q1Satisfaction: 82,
    q2Satisfaction: 85,
    q3Satisfaction: 87,
    q4Satisfaction: 89,
  },
  {
    department: "Sales",
    q1Revenue: 4200000,
    q2Revenue: 4650000,
    q3Revenue: 5100000,
    q4Revenue: 5580000,
    q1Completion: 91,
    q2Completion: 94,
    q3Completion: 96,
    q4Completion: 98,
    q1Satisfaction: 84,
    q2Satisfaction: 86,
    q3Satisfaction: 88,
    q4Satisfaction: 91,
  },
  {
    department: "HR",
    q1Revenue: 850000,
    q2Revenue: 920000,
    q3Revenue: 980000,
    q4Revenue: 1050000,
    q1Completion: 88,
    q2Completion: 90,
    q3Completion: 93,
    q4Completion: 95,
    q1Satisfaction: 89,
    q2Satisfaction: 91,
    q3Satisfaction: 93,
    q4Satisfaction: 95,
  },
  {
    department: "Finance",
    q1Revenue: 1200000,
    q2Revenue: 1280000,
    q3Revenue: 1350000,
    q4Revenue: 1420000,
    q1Completion: 86,
    q2Completion: 88,
    q3Completion: 90,
    q4Completion: 92,
    q1Satisfaction: 81,
    q2Satisfaction: 83,
    q3Satisfaction: 85,
    q4Satisfaction: 87,
  },
  {
    department: "Operations",
    q1Revenue: 1950000,
    q2Revenue: 2100000,
    q3Revenue: 2280000,
    q4Revenue: 2450000,
    q1Completion: 83,
    q2Completion: 86,
    q3Completion: 89,
    q4Completion: 91,
    q1Satisfaction: 79,
    q2Satisfaction: 81,
    q3Satisfaction: 84,
    q4Satisfaction: 86,
  },
  {
    department: "Customer Support",
    q1Revenue: 980000,
    q2Revenue: 1080000,
    q3Revenue: 1180000,
    q4Revenue: 1290000,
    q1Completion: 90,
    q2Completion: 92,
    q3Completion: 94,
    q4Completion: 96,
    q1Satisfaction: 86,
    q2Satisfaction: 88,
    q3Satisfaction: 90,
    q4Satisfaction: 92,
  },
  {
    department: "Product",
    q1Revenue: 2200000,
    q2Revenue: 2450000,
    q3Revenue: 2720000,
    q4Revenue: 3000000,
    q1Completion: 92,
    q2Completion: 94,
    q3Completion: 96,
    q4Completion: 98,
    q1Satisfaction: 91,
    q2Satisfaction: 93,
    q3Satisfaction: 95,
    q4Satisfaction: 97,
  },
]

// Additional Analytics Data

// Team Productivity Metrics
export const teamProductivityData = [
  {
    team: "Frontend Development",
    productivity: 92,
    velocity: 85,
    qualityScore: 88,
    burnoutRisk: 15,
  },
  {
    team: "Backend Development",
    productivity: 89,
    velocity: 91,
    qualityScore: 94,
    burnoutRisk: 12,
  },
  {
    team: "QA Testing",
    productivity: 87,
    velocity: 83,
    qualityScore: 96,
    burnoutRisk: 18,
  },
  {
    team: "DevOps",
    productivity: 94,
    velocity: 88,
    qualityScore: 91,
    burnoutRisk: 10,
  },
  {
    team: "Design",
    productivity: 85,
    velocity: 79,
    qualityScore: 93,
    burnoutRisk: 22,
  },
]

// Employee Satisfaction Trends
export const satisfactionTrendsData = [
  { month: "Jan", workLifeBalance: 78, compensation: 82, growth: 75, management: 80 },
  { month: "Feb", workLifeBalance: 80, compensation: 83, growth: 77, management: 82 },
  { month: "Mar", workLifeBalance: 82, compensation: 84, growth: 79, management: 84 },
  { month: "Apr", workLifeBalance: 81, compensation: 85, growth: 78, management: 83 },
  { month: "May", workLifeBalance: 84, compensation: 86, growth: 81, management: 85 },
  { month: "Jun", workLifeBalance: 86, compensation: 87, growth: 83, management: 87 },
  { month: "Jul", workLifeBalance: 85, compensation: 88, growth: 82, management: 86 },
  { month: "Aug", workLifeBalance: 87, compensation: 89, growth: 84, management: 88 },
  { month: "Sep", workLifeBalance: 89, compensation: 90, growth: 86, management: 90 },
  { month: "Oct", workLifeBalance: 88, compensation: 91, growth: 85, management: 89 },
  { month: "Nov", workLifeBalance: 90, compensation: 92, growth: 87, management: 91 },
  { month: "Dec", workLifeBalance: 91, compensation: 93, growth: 88, management: 92 },
]

// Training and Development Data
export const trainingDevelopmentData = [
  {
    program: "Leadership Development",
    participants: 45,
    completionRate: 89,
    satisfactionScore: 4.3,
    impactScore: 87,
    cost: 125000,
  },
  {
    program: "Technical Skills",
    participants: 78,
    completionRate: 92,
    satisfactionScore: 4.5,
    impactScore: 91,
    cost: 180000,
  },
  {
    program: "Communication Skills",
    participants: 62,
    completionRate: 94,
    satisfactionScore: 4.2,
    impactScore: 85,
    cost: 95000,
  },
  {
    program: "Project Management",
    participants: 38,
    completionRate: 87,
    satisfactionScore: 4.1,
    impactScore: 83,
    cost: 110000,
  },
  {
    program: "Digital Transformation",
    participants: 55,
    completionRate: 91,
    satisfactionScore: 4.4,
    impactScore: 89,
    cost: 165000,
  },
]
